### ISSUE TITLE
YAY!!!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s3-evaluacion-intermedia-garcaplay#1]
Well done @garcaplay!

Some tips to improve it:

- [x] Move `li` outside 'Pokemon' component, this way it is a simple card that we can use anywhere not only inside a `ul`
- [x] Add title of the page (Mi lista de Pokemons)
- [x] Use `id` of pokemon for the `key` of React when mapping
- [x] Review metadata on index.html (lang, title...)

Go for it!

**Comment by garcaplay** [comment]
Thank you for the feedback!!
